module.exports = (sequelize, DataTypes) => {
  const CoinPurchaseOrder = sequelize.define("CoinPurchaseOrder", {
    purchase_id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true,
    },
    user_id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      references: {
        model: "Users",
        key: "user_id",
      },
    },
    plan_id: {
      type: DataTypes.INTEGER,
      allowNull: true,
      references: {
        model: "Transaction_plans",
        key: "plan_id",
      },
      comment: "Reference to the purchased plan",
    },
    order_id: {
      type: DataTypes.STRING,
      allowNull: false,
      comment: "NOWPayments order ID",
    },
    payment_id: {
      type: DataTypes.STRING,
      allowNull: true,
      comment: "NOWPayments payment ID",
    },
    coins: {
      type: DataTypes.INTEGER,
      allowNull: false,
      validate: {
        min: 1,
      },
      comment: "Number of coins to be purchased",
    },
    amount_usd: {
      type: DataTypes.DECIMAL(10, 2),
      allowNull: false,
      validate: {
        min: 0,
      },
      comment: "Amount in USD",
    },
    currency: {
      type: DataTypes.STRING,
      allowNull: false,
      defaultValue: "USD",
      comment: "Cryptocurrency or fiat currency",
    },
    pay_currency: {
      type: DataTypes.STRING,
      allowNull: false,
      comment: "Currency specified by NOWPayments",
    },
    pay_amount: {
      type: DataTypes.DECIMAL(18, 8),
      allowNull: true,
      comment: "Amount in the pay_currency",
    },
    status: {
      type: DataTypes.STRING, // ✅ CHANGE THIS
      allowNull: false,
      defaultValue: "PENDING",
      validate: {
        isIn: [[
          "PENDING",
          "CONFIRMING",
          "CONFIRMED",
          "SENDING",
          "FINISHED",
          "FAILED",
          "CANCELLED"
        ]]
      }
    },
    confirmation_count: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0,
      comment: "Number of block confirmations",
    },
    payment_address: {
      type: DataTypes.STRING,
      allowNull: true,
      comment: "Payment address generated by NOWPayments",
    },
    ipn_callback_url: {
      type: DataTypes.STRING,
      allowNull: true,
      comment: "IPN callback URL",
    },
    success_url: {
      type: DataTypes.STRING,
      allowNull: true,
      comment: "Success redirect URL",
    },
    cancel_url: {
      type: DataTypes.STRING,
      allowNull: true,
      comment: "Cancellation redirect URL",
    },
    coins_added: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: false,
      comment: "Whether coins have been credited to user",
    },
    webhook_count: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0,
      comment: "Number of webhook calls received for this order",
    },
    last_webhook_at: {
      type: DataTypes.DATE,
      allowNull: true,
      comment: "Timestamp of last webhook call",
    },
    error_message: {
      type: DataTypes.TEXT,
      allowNull: true,
      comment: "Error message if payment failed",
    },
    created_at: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW,
    },
    updated_at: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW,
    },
  });

  return CoinPurchaseOrder;
};
